on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge feature branch to main"
          branch: main
          title: "Feature Pull Request"
          body: |
            This pull request merges changes from a feature branch to the main branch.
          base: main
          branch-suffix: feature

